# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/claim_recipient.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)inference/inference/claim_recipient.proto\x12\x13inference.inference\"I\n\x13\x43laimRecipientEntry\x12\x14\n\x05\x65poch\x18\x01 \x01(\x04R\x05\x65poch\x12\x1c\n\trecipient\x18\x02 \x01(\tR\trecipientB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.claim_recipient_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_CLAIMRECIPIENTENTRY']._serialized_start=66
  _globals['_CLAIMRECIPIENTENTRY']._serialized_end=139
# @@protoc_insertion_point(module_scope)
