# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/epoch_group_datav1.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from inference.inference import participant_pb2 as inference_dot_inference_dot_participant__pb2
from inference.inference import paramsv1_pb2 as inference_dot_inference_dot_paramsv1__pb2
from inference.inference import epoch_group_data_pb2 as inference_dot_inference_dot_epoch__group__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,inference/inference/epoch_group_datav1.proto\x12\x13inference.inference\x1a%inference/inference/participant.proto\x1a\"inference/inference/paramsv1.proto\x1a*inference/inference/epoch_group_data.proto\"\xb4\x05\n\x10\x45pochGroupDataV1\x12\x33\n\x16poc_start_block_height\x18\x01 \x01(\x04R\x13pocStartBlockHeight\x12$\n\x0e\x65poch_group_id\x18\x02 \x01(\x04R\x0c\x65pochGroupId\x12!\n\x0c\x65poch_policy\x18\x03 \x01(\tR\x0b\x65pochPolicy\x12\x34\n\x16\x65\x66\x66\x65\x63tive_block_height\x18\x04 \x01(\x04R\x14\x65\x66\x66\x65\x63tiveBlockHeight\x12*\n\x11last_block_height\x18\x05 \x01(\x04R\x0flastBlockHeight\x12X\n\x16member_seed_signatures\x18\x06 \x03(\x0b\x32\".inference.inference.SeedSignatureR\x14memberSeedSignatures\x12T\n\x12validation_weights\x18\x08 \x03(\x0b\x32%.inference.inference.ValidationWeightR\x11validationWeights\x12\x31\n\x15unit_of_compute_price\x18\t \x01(\x04R\x12unitOfComputePrice\x12,\n\x12number_of_requests\x18\n \x01(\x04R\x10numberOfRequests\x12\x36\n\x17previous_epoch_requests\x18\x0b \x01(\x04R\x15previousEpochRequests\x12T\n\x11validation_params\x18\x0c \x01(\x0b\x32\'.inference.inference.ValidationParamsV1R\x10validationParams\x12!\n\x0ctotal_weight\x18\r \x01(\x04R\x0btotalWeightB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.epoch_group_datav1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_EPOCHGROUPDATAV1']._serialized_start=189
  _globals['_EPOCHGROUPDATAV1']._serialized_end=881
# @@protoc_insertion_point(module_scope)
