# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/maintenance.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%inference/inference/maintenance.proto\x12\x13inference.inference\"\xc6\x02\n\x16MaintenanceReservation\x12%\n\x0ereservation_id\x18\x01 \x01(\x04R\rreservationId\x12 \n\x0bparticipant\x18\x02 \x01(\tR\x0bparticipant\x12!\n\x0cstart_height\x18\x03 \x01(\x03R\x0bstartHeight\x12\'\n\x0f\x64uration_blocks\x18\x04 \x01(\x04R\x0e\x64urationBlocks\x12\x1d\n\ncreated_by\x18\x05 \x01(\tR\tcreatedBy\x12I\n\x06status\x18\x06 \x01(\x0e\x32\x31.inference.inference.MaintenanceReservationStatusR\x06status\x12-\n\x12\x61\x63tivation_warning\x18\x07 \x01(\tR\x11\x61\x63tivationWarning\"\xba\x02\n\x10MaintenanceState\x12 \n\x0bparticipant\x18\x01 \x01(\tR\x0bparticipant\x12#\n\rcredit_blocks\x18\x02 \x01(\x04R\x0c\x63reditBlocks\x12\x34\n\x16last_maintenance_epoch\x18\x03 \x01(\x04R\x14lastMaintenanceEpoch\x12\x32\n\x15\x61\x63tive_reservation_id\x18\x04 \x01(\x04R\x13\x61\x63tiveReservationId\x12\x38\n\x18scheduled_reservation_id\x18\x05 \x01(\x04R\x16scheduledReservationId\x12;\n\x1alast_maintenance_end_epoch\x18\x06 \x01(\x04R\x17lastMaintenanceEndEpoch\"\xa5\x01\n\x15MaintenanceTransition\x12!\n\x0c\x62lock_height\x18\x01 \x01(\x03R\x0b\x62lockHeight\x12%\n\x0ereservation_id\x18\x02 \x01(\x04R\rreservationId\x12\x42\n\x04type\x18\x03 \x01(\x0e\x32..inference.inference.MaintenanceTransitionTypeR\x04type*\x82\x02\n\x1cMaintenanceReservationStatus\x12.\n*MAINTENANCE_RESERVATION_STATUS_UNSPECIFIED\x10\x00\x12,\n(MAINTENANCE_RESERVATION_STATUS_SCHEDULED\x10\x01\x12)\n%MAINTENANCE_RESERVATION_STATUS_ACTIVE\x10\x02\x12,\n(MAINTENANCE_RESERVATION_STATUS_COMPLETED\x10\x03\x12+\n\'MAINTENANCE_RESERVATION_STATUS_CANCELED\x10\x04*\x9c\x01\n\x19MaintenanceTransitionType\x12+\n\'MAINTENANCE_TRANSITION_TYPE_UNSPECIFIED\x10\x00\x12(\n$MAINTENANCE_TRANSITION_TYPE_ACTIVATE\x10\x01\x12(\n$MAINTENANCE_TRANSITION_TYPE_COMPLETE\x10\x02\x42\x37Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.maintenance_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_MAINTENANCERESERVATIONSTATUS']._serialized_start=877
  _globals['_MAINTENANCERESERVATIONSTATUS']._serialized_end=1135
  _globals['_MAINTENANCETRANSITIONTYPE']._serialized_start=1138
  _globals['_MAINTENANCETRANSITIONTYPE']._serialized_end=1294
  _globals['_MAINTENANCERESERVATION']._serialized_start=63
  _globals['_MAINTENANCERESERVATION']._serialized_end=389
  _globals['_MAINTENANCESTATE']._serialized_start=392
  _globals['_MAINTENANCESTATE']._serialized_end=706
  _globals['_MAINTENANCETRANSITION']._serialized_start=709
  _globals['_MAINTENANCETRANSITION']._serialized_end=874
# @@protoc_insertion_point(module_scope)
