# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/poc_validation_snapshot.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1inference/inference/poc_validation_snapshot.proto\x12\x13inference.inference\"\xd7\x02\n\x15PoCValidationSnapshot\x12\x33\n\x16poc_stage_start_height\x18\x01 \x01(\x03R\x13pocStageStartHeight\x12\'\n\x0fsnapshot_height\x18\x02 \x01(\x03R\x0esnapshotHeight\x12\x19\n\x08\x61pp_hash\x18\x03 \x01(\tR\x07\x61ppHash\x12Q\n\x11validator_weights\x18\x04 \x03(\x0b\x32$.inference.inference.ValidatorWeightR\x10validatorWeights\x12<\n\x1ageneration_start_timestamp\x18\x05 \x01(\x03R\x18generationStartTimestamp\x12\x34\n\x16\x65xchange_end_timestamp\x18\x06 \x01(\x03R\x14\x65xchangeEndTimestamp\"C\n\x0fValidatorWeight\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\x12\x16\n\x06weight\x18\x02 \x01(\x03R\x06weightB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.poc_validation_snapshot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_POCVALIDATIONSNAPSHOT']._serialized_start=75
  _globals['_POCVALIDATIONSNAPSHOT']._serialized_end=418
  _globals['_VALIDATORWEIGHT']._serialized_start=420
  _globals['_VALIDATORWEIGHT']._serialized_end=487
# @@protoc_insertion_point(module_scope)
