# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/poc_v2.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n inference/inference/poc_v2.proto\x12\x13inference.inference\"=\n\rPoCArtifactV2\x12\x14\n\x05nonce\x18\x01 \x01(\x05R\x05nonce\x12\x16\n\x06vector\x18\x02 \x01(\x0cR\x06vector\"\xf1\x01\n\x0fPoCValidationV2\x12/\n\x13participant_address\x18\x01 \x01(\tR\x12participantAddress\x12\x42\n\x1dvalidator_participant_address\x18\x02 \x01(\tR\x1bvalidatorParticipantAddress\x12>\n\x1cpoc_stage_start_block_height\x18\x03 \x01(\x03R\x18pocStageStartBlockHeight\x12)\n\x10validated_weight\x18\x04 \x01(\x03R\x0fvalidatedWeight\"t\n\x16PoCValidationPayloadV2\x12/\n\x13participant_address\x18\x01 \x01(\tR\x12participantAddress\x12)\n\x10validated_weight\x18\x02 \x01(\x03R\x0fvalidatedWeight\"?\n\x0cMLNodeWeight\x12\x17\n\x07node_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n\x06weight\x18\x02 \x01(\rR\x06weight\"\xe6\x01\n\x10PoCV2StoreCommit\x12/\n\x13participant_address\x18\x01 \x01(\tR\x12participantAddress\x12>\n\x1cpoc_stage_start_block_height\x18\x02 \x01(\x03R\x18pocStageStartBlockHeight\x12\x14\n\x05\x63ount\x18\x03 \x01(\rR\x05\x63ount\x12\x1b\n\troot_hash\x18\x04 \x01(\x0cR\x08rootHash\x12.\n\x13\x63ommit_block_height\x18\x05 \x01(\x03R\x11\x63ommitBlockHeight\"\xc8\x01\n\x18MLNodeWeightDistribution\x12/\n\x13participant_address\x18\x01 \x01(\tR\x12participantAddress\x12>\n\x1cpoc_stage_start_block_height\x18\x02 \x01(\x03R\x18pocStageStartBlockHeight\x12;\n\x07weights\x18\x03 \x03(\x0b\x32!.inference.inference.MLNodeWeightR\x07weightsB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.poc_v2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_POCARTIFACTV2']._serialized_start=57
  _globals['_POCARTIFACTV2']._serialized_end=118
  _globals['_POCVALIDATIONV2']._serialized_start=121
  _globals['_POCVALIDATIONV2']._serialized_end=362
  _globals['_POCVALIDATIONPAYLOADV2']._serialized_start=364
  _globals['_POCVALIDATIONPAYLOADV2']._serialized_end=480
  _globals['_MLNODEWEIGHT']._serialized_start=482
  _globals['_MLNODEWEIGHT']._serialized_end=545
  _globals['_POCV2STORECOMMIT']._serialized_start=548
  _globals['_POCV2STORECOMMIT']._serialized_end=778
  _globals['_MLNODEWEIGHTDISTRIBUTION']._serialized_start=781
  _globals['_MLNODEWEIGHTDISTRIBUTION']._serialized_end=981
# @@protoc_insertion_point(module_scope)
