# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/pruning_state.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'inference/inference/pruning_state.proto\x12\x13inference.inference\"\xbe\x01\n\x0cPruningState\x12\x37\n\x18poc_batches_pruned_epoch\x18\x01 \x01(\x03R\x15pocBatchesPrunedEpoch\x12?\n\x1cpoc_validations_pruned_epoch\x18\x02 \x01(\x03R\x19pocValidationsPrunedEpoch\x12\x34\n\x16inference_pruned_epoch\x18\x03 \x01(\x03R\x14inferencePrunedEpochB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.pruning_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_PRUNINGSTATE']._serialized_start=65
  _globals['_PRUNINGSTATE']._serialized_end=255
# @@protoc_insertion_point(module_scope)
