# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/subnet_settlement.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+inference/inference/subnet_settlement.proto\x12\x13inference.inference\"\xdd\x01\n\x14SubnetHostStatsProto\x12\x17\n\x07slot_id\x18\x01 \x01(\rR\x06slotId\x12\x16\n\x06missed\x18\x02 \x01(\rR\x06missed\x12\x18\n\x07invalid\x18\x03 \x01(\rR\x07invalid\x12\x12\n\x04\x63ost\x18\x04 \x01(\x04R\x04\x63ost\x12\x31\n\x14required_validations\x18\x05 \x01(\rR\x13requiredValidations\x12\x33\n\x15\x63ompleted_validations\x18\x06 \x01(\rR\x14\x63ompletedValidations\"^\n\x17SubnetHostStatsMapProto\x12\x43\n\x07\x65ntries\x18\x01 \x03(\x0b\x32).inference.inference.SubnetHostStatsProtoR\x07\x65ntries\"o\n\x1bSubnetStateSignatureContent\x12\x1d\n\nstate_root\x18\x01 \x01(\x0cR\tstateRoot\x12\x1b\n\tescrow_id\x18\x02 \x01(\tR\x08\x65scrowId\x12\x14\n\x05nonce\x18\x03 \x01(\x04R\x05nonceB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.subnet_settlement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_SUBNETHOSTSTATSPROTO']._serialized_start=69
  _globals['_SUBNETHOSTSTATSPROTO']._serialized_end=290
  _globals['_SUBNETHOSTSTATSMAPPROTO']._serialized_start=292
  _globals['_SUBNETHOSTSTATSMAPPROTO']._serialized_end=386
  _globals['_SUBNETSTATESIGNATURECONTENT']._serialized_start=388
  _globals['_SUBNETSTATESIGNATURECONTENT']._serialized_end=499
# @@protoc_insertion_point(module_scope)
