# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/tokenomics_data.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)inference/inference/tokenomics_data.proto\x12\x13inference.inference\"\xcc\x01\n\x0eTokenomicsData\x12\x1d\n\ntotal_fees\x18\x01 \x01(\x04R\ttotalFees\x12\'\n\x0ftotal_subsidies\x18\x02 \x01(\x04R\x0etotalSubsidies\x12%\n\x0etotal_refunded\x18\x03 \x01(\x04R\rtotalRefunded\x12!\n\x0ctotal_burned\x18\x04 \x01(\x04R\x0btotalBurned\x12(\n\x10top_reward_start\x18\x05 \x01(\x03R\x0etopRewardStartB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.tokenomics_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_TOKENOMICSDATA']._serialized_start=67
  _globals['_TOKENOMICSDATA']._serialized_end=271
# @@protoc_insertion_point(module_scope)
