# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference/inference/training_task_sync.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,inference/inference/training_task_sync.proto\x12\x13inference.inference\"y\n\x14TrainingTaskKVRecord\x12\x17\n\x07task_id\x18\x01 \x01(\x04R\x06taskId\x12 \n\x0bparticipant\x18\x02 \x01(\tR\x0bparticipant\x12\x10\n\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n\x05value\x18\x04 \x01(\tR\x05value\"\xd1\x01\n\x1dTrainingTaskNodeEpochActivity\x12\x17\n\x07task_id\x18\x01 \x01(\x04R\x06taskId\x12 \n\x0bparticipant\x18\x02 \x01(\tR\x0bparticipant\x12\x17\n\x07node_id\x18\x03 \x01(\tR\x06nodeId\x12\x12\n\x04rank\x18\x04 \x01(\x05R\x04rank\x12H\n\theartbeat\x18\x05 \x01(\x0b\x32*.inference.inference.TrainingTaskHeartbeatR\theartbeat\"\xad\x01\n\x15TrainingTaskHeartbeat\x12\x1d\n\ninner_step\x18\x01 \x01(\x05R\tinnerStep\x12\x1d\n\nouter_step\x18\x02 \x01(\x05R\touterStep\x12\x14\n\x05\x65poch\x18\x03 \x01(\x05R\x05\x65poch\x12!\n\x0c\x62lock_height\x18\x04 \x01(\x03R\x0b\x62lockHeight\x12\x1d\n\nblock_time\x18\x05 \x01(\x03R\tblockTime\"\xe9\x01\n\x13TrainingTaskBarrier\x12\x1d\n\nbarrier_id\x18\x01 \x01(\tR\tbarrierId\x12\x17\n\x07task_id\x18\x02 \x01(\x04R\x06taskId\x12 \n\x0bparticipant\x18\x03 \x01(\tR\x0bparticipant\x12\x17\n\x07node_id\x18\x04 \x01(\tR\x06nodeId\x12\x1d\n\nouter_step\x18\x05 \x01(\x05R\touterStep\x12!\n\x0c\x62lock_height\x18\x06 \x01(\x03R\x0b\x62lockHeight\x12\x1d\n\nblock_time\x18\x07 \x01(\x03R\tblockTimeB7Z5github.com/productscience/inference/x/inference/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference.inference.training_task_sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/productscience/inference/x/inference/types'
  _globals['_TRAININGTASKKVRECORD']._serialized_start=69
  _globals['_TRAININGTASKKVRECORD']._serialized_end=190
  _globals['_TRAININGTASKNODEEPOCHACTIVITY']._serialized_start=193
  _globals['_TRAININGTASKNODEEPOCHACTIVITY']._serialized_end=402
  _globals['_TRAININGTASKHEARTBEAT']._serialized_start=405
  _globals['_TRAININGTASKHEARTBEAT']._serialized_end=578
  _globals['_TRAININGTASKBARRIER']._serialized_start=581
  _globals['_TRAININGTASKBARRIER']._serialized_end=814
# @@protoc_insertion_point(module_scope)
