# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/gmp/v1/account.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%ibc/applications/gmp/v1/account.proto\x12\x17ibc.applications.gmp.v1\x1a\x19google/protobuf/any.proto\x1a\x19\x63osmos_proto/cosmos.proto\"\\\n\x11\x41\x63\x63ountIdentifier\x12\x1b\n\tclient_id\x18\x01 \x01(\tR\x08\x63lientId\x12\x16\n\x06sender\x18\x02 \x01(\tR\x06sender\x12\x12\n\x04salt\x18\x03 \x01(\x0cR\x04salt\"\x8d\x01\n\x0cICS27Account\x12\x32\n\x07\x61\x64\x64ress\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x07\x61\x64\x64ress\x12I\n\naccount_id\x18\x02 \x01(\x0b\x32*.ibc.applications.gmp.v1.AccountIdentifierR\taccountId\"<\n\x08\x43osmosTx\x12\x30\n\x08messages\x18\x01 \x03(\x0b\x32\x14.google.protobuf.AnyR\x08messagesB8Z6github.com/cosmos/ibc-go/v10/modules/apps/27-gmp/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.applications.gmp.v1.account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/cosmos/ibc-go/v10/modules/apps/27-gmp/types'
  _globals['_ICS27ACCOUNT'].fields_by_name['address']._loaded_options = None
  _globals['_ICS27ACCOUNT'].fields_by_name['address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_ACCOUNTIDENTIFIER']._serialized_start=120
  _globals['_ACCOUNTIDENTIFIER']._serialized_end=212
  _globals['_ICS27ACCOUNT']._serialized_start=215
  _globals['_ICS27ACCOUNT']._serialized_end=356
  _globals['_COSMOSTX']._serialized_start=358
  _globals['_COSMOSTX']._serialized_end=418
# @@protoc_insertion_point(module_scope)
