# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/gmp/v1/genesis.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ibc.applications.gmp.v1 import account_pb2 as ibc_dot_applications_dot_gmp_dot_v1_dot_account__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%ibc/applications/gmp/v1/genesis.proto\x12\x17ibc.applications.gmp.v1\x1a%ibc/applications/gmp/v1/account.proto\x1a\x14gogoproto/gogo.proto\"l\n\x0cGenesisState\x12\\\n\x0eics27_accounts\x18\x02 \x03(\x0b\x32/.ibc.applications.gmp.v1.RegisteredICS27AccountB\x04\xc8\xde\x1f\x00R\rics27Accounts\"\x92\x01\n\x16RegisteredICS27Account\x12\'\n\x0f\x61\x63\x63ount_address\x18\x01 \x01(\tR\x0e\x61\x63\x63ountAddress\x12O\n\naccount_id\x18\x02 \x01(\x0b\x32*.ibc.applications.gmp.v1.AccountIdentifierB\x04\xc8\xde\x1f\x00R\taccountIdB8Z6github.com/cosmos/ibc-go/v10/modules/apps/27-gmp/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.applications.gmp.v1.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/cosmos/ibc-go/v10/modules/apps/27-gmp/types'
  _globals['_GENESISSTATE'].fields_by_name['ics27_accounts']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['ics27_accounts']._serialized_options = b'\310\336\037\000'
  _globals['_REGISTEREDICS27ACCOUNT'].fields_by_name['account_id']._loaded_options = None
  _globals['_REGISTEREDICS27ACCOUNT'].fields_by_name['account_id']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=127
  _globals['_GENESISSTATE']._serialized_end=235
  _globals['_REGISTEREDICS27ACCOUNT']._serialized_start=238
  _globals['_REGISTEREDICS27ACCOUNT']._serialized_end=384
# @@protoc_insertion_point(module_scope)
