# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/gmp/v1/packet.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$ibc/applications/gmp/v1/packet.proto\x12\x17ibc.applications.gmp.v1\"\x85\x01\n\rGMPPacketData\x12\x16\n\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1a\n\x08receiver\x18\x02 \x01(\tR\x08receiver\x12\x12\n\x04salt\x18\x03 \x01(\x0cR\x04salt\x12\x18\n\x07payload\x18\x04 \x01(\x0cR\x07payload\x12\x12\n\x04memo\x18\x05 \x01(\tR\x04memo\")\n\x0f\x41\x63knowledgement\x12\x16\n\x06result\x18\x01 \x01(\x0cR\x06resultB8Z6github.com/cosmos/ibc-go/v10/modules/apps/27-gmp/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.applications.gmp.v1.packet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/cosmos/ibc-go/v10/modules/apps/27-gmp/types'
  _globals['_GMPPACKETDATA']._serialized_start=66
  _globals['_GMPPACKETDATA']._serialized_end=199
  _globals['_ACKNOWLEDGEMENT']._serialized_start=201
  _globals['_ACKNOWLEDGEMENT']._serialized_end=242
# @@protoc_insertion_point(module_scope)
