# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/gmp/v1/query.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from ibc.applications.gmp.v1 import account_pb2 as ibc_dot_applications_dot_gmp_dot_v1_dot_account__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ibc/applications/gmp/v1/query.proto\x12\x17ibc.applications.gmp.v1\x1a\x1cgoogle/api/annotations.proto\x1a%ibc/applications/gmp/v1/account.proto\"e\n\x1aQueryAccountAddressRequest\x12\x1b\n\tclient_id\x18\x01 \x01(\tR\x08\x63lientId\x12\x16\n\x06sender\x18\x02 \x01(\tR\x06sender\x12\x12\n\x04salt\x18\x03 \x01(\tR\x04salt\"F\n\x1bQueryAccountAddressResponse\x12\'\n\x0f\x61\x63\x63ount_address\x18\x01 \x01(\tR\x0e\x61\x63\x63ountAddress\"H\n\x1dQueryAccountIdentifierRequest\x12\'\n\x0f\x61\x63\x63ount_address\x18\x01 \x01(\tR\x0e\x61\x63\x63ountAddress\"k\n\x1eQueryAccountIdentifierResponse\x12I\n\naccount_id\x18\x01 \x01(\x0b\x32*.ibc.applications.gmp.v1.AccountIdentifierR\taccountId2\x96\x03\n\x05Query\x12\xc5\x01\n\x0e\x41\x63\x63ountAddress\x12\x33.ibc.applications.gmp.v1.QueryAccountAddressRequest\x1a\x34.ibc.applications.gmp.v1.QueryAccountAddressResponse\"H\x82\xd3\xe4\x93\x02\x42\x12@/ibc/apps/gmp/v1/clients/{client_id}/accounts/{sender}/{salt=**}\x12\xc4\x01\n\x11\x41\x63\x63ountIdentifier\x12\x36.ibc.applications.gmp.v1.QueryAccountIdentifierRequest\x1a\x37.ibc.applications.gmp.v1.QueryAccountIdentifierResponse\">\x82\xd3\xe4\x93\x02\x38\x12\x36/ibc/apps/gmp/v1/accounts/{account_address}/identifierB8Z6github.com/cosmos/ibc-go/v10/modules/apps/27-gmp/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.applications.gmp.v1.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/cosmos/ibc-go/v10/modules/apps/27-gmp/types'
  _globals['_QUERY'].methods_by_name['AccountAddress']._loaded_options = None
  _globals['_QUERY'].methods_by_name['AccountAddress']._serialized_options = b'\202\323\344\223\002B\022@/ibc/apps/gmp/v1/clients/{client_id}/accounts/{sender}/{salt=**}'
  _globals['_QUERY'].methods_by_name['AccountIdentifier']._loaded_options = None
  _globals['_QUERY'].methods_by_name['AccountIdentifier']._serialized_options = b'\202\323\344\223\0028\0226/ibc/apps/gmp/v1/accounts/{account_address}/identifier'
  _globals['_QUERYACCOUNTADDRESSREQUEST']._serialized_start=133
  _globals['_QUERYACCOUNTADDRESSREQUEST']._serialized_end=234
  _globals['_QUERYACCOUNTADDRESSRESPONSE']._serialized_start=236
  _globals['_QUERYACCOUNTADDRESSRESPONSE']._serialized_end=306
  _globals['_QUERYACCOUNTIDENTIFIERREQUEST']._serialized_start=308
  _globals['_QUERYACCOUNTIDENTIFIERREQUEST']._serialized_end=380
  _globals['_QUERYACCOUNTIDENTIFIERRESPONSE']._serialized_start=382
  _globals['_QUERYACCOUNTIDENTIFIERRESPONSE']._serialized_end=489
  _globals['_QUERY']._serialized_start=492
  _globals['_QUERY']._serialized_end=898
# @@protoc_insertion_point(module_scope)
