# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/gmp/v1/tx.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n ibc/applications/gmp/v1/tx.proto\x12\x17ibc.applications.gmp.v1\x1a\x14gogoproto/gogo.proto\x1a\x17\x63osmos/msg/v1/msg.proto\"\x82\x02\n\x0bMsgSendCall\x12#\n\rsource_client\x18\x01 \x01(\tR\x0csourceClient\x12\x16\n\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1a\n\x08receiver\x18\x03 \x01(\tR\x08receiver\x12\x12\n\x04salt\x18\x04 \x01(\x0cR\x04salt\x12\x18\n\x07payload\x18\x05 \x01(\x0cR\x07payload\x12+\n\x11timeout_timestamp\x18\x06 \x01(\x04R\x10timeoutTimestamp\x12\x12\n\x04memo\x18\x07 \x01(\tR\x04memo\x12\x1a\n\x08\x65ncoding\x18\x08 \x01(\tR\x08\x65ncoding:\x0f\x88\xa0\x1f\x00\x82\xe7\xb0*\x06sender\"7\n\x13MsgSendCallResponse\x12\x1a\n\x08sequence\x18\x01 \x01(\x04R\x08sequence:\x04\x88\xa0\x1f\x00\x32l\n\x03Msg\x12^\n\x08SendCall\x12$.ibc.applications.gmp.v1.MsgSendCall\x1a,.ibc.applications.gmp.v1.MsgSendCallResponse\x1a\x05\x80\xe7\xb0*\x01\x42\x38Z6github.com/cosmos/ibc-go/v10/modules/apps/27-gmp/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.applications.gmp.v1.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/cosmos/ibc-go/v10/modules/apps/27-gmp/types'
  _globals['_MSGSENDCALL']._loaded_options = None
  _globals['_MSGSENDCALL']._serialized_options = b'\210\240\037\000\202\347\260*\006sender'
  _globals['_MSGSENDCALLRESPONSE']._loaded_options = None
  _globals['_MSGSENDCALLRESPONSE']._serialized_options = b'\210\240\037\000'
  _globals['_MSG']._loaded_options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSGSENDCALL']._serialized_start=109
  _globals['_MSGSENDCALL']._serialized_end=367
  _globals['_MSGSENDCALLRESPONSE']._serialized_start=369
  _globals['_MSGSENDCALLRESPONSE']._serialized_end=424
  _globals['_MSG']._serialized_start=426
  _globals['_MSG']._serialized_end=534
# @@protoc_insertion_point(module_scope)
