# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/applications/rate_limiting/v1/genesis.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from ibc.applications.rate_limiting.v1 import rate_limiting_pb2 as ibc_dot_applications_dot_rate__limiting_dot_v1_dot_rate__limiting__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/ibc/applications/rate_limiting/v1/genesis.proto\x12!ibc.applications.rate_limiting.v1\x1a\x14gogoproto/gogo.proto\x1a\x35ibc/applications/rate_limiting/v1/rate_limiting.proto\"\xb2\x03\n\x0cGenesisState\x12S\n\x0brate_limits\x18\x01 \x03(\x0b\x32,.ibc.applications.rate_limiting.v1.RateLimitB\x04\xc8\xde\x1f\x00R\nrateLimits\x12{\n\x19whitelisted_address_pairs\x18\x02 \x03(\x0b\x32\x39.ibc.applications.rate_limiting.v1.WhitelistedAddressPairB\x04\xc8\xde\x1f\x00R\x17whitelistedAddressPairs\x12-\n\x12\x62lacklisted_denoms\x18\x03 \x03(\tR\x11\x62lacklistedDenoms\x12N\n$pending_send_packet_sequence_numbers\x18\x04 \x03(\tR pendingSendPacketSequenceNumbers\x12Q\n\nhour_epoch\x18\x05 \x01(\x0b\x32,.ibc.applications.rate_limiting.v1.HourEpochB\x04\xc8\xde\x1f\x00R\thourEpochB?Z=github.com/cosmos/ibc-go/v10/modules/apps/rate-limiting/typesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.applications.rate_limiting.v1.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/cosmos/ibc-go/v10/modules/apps/rate-limiting/types'
  _globals['_GENESISSTATE'].fields_by_name['rate_limits']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['rate_limits']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['whitelisted_address_pairs']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['whitelisted_address_pairs']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['hour_epoch']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['hour_epoch']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=164
  _globals['_GENESISSTATE']._serialized_end=598
# @@protoc_insertion_point(module_scope)
