# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/lightclients/attestations/v1/attestations.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3ibc/lightclients/attestations/v1/attestations.proto\x12 ibc.lightclients.attestations.v1\x1a\x14gogoproto/gogo.proto\"\xb0\x01\n\x0b\x43lientState\x12-\n\x12\x61ttestor_addresses\x18\x01 \x03(\tR\x11\x61ttestorAddresses\x12*\n\x11min_required_sigs\x18\x02 \x01(\rR\x0fminRequiredSigs\x12#\n\rlatest_height\x18\x03 \x01(\x04R\x0clatestHeight\x12\x1b\n\tis_frozen\x18\x04 \x01(\x08R\x08isFrozen:\x04\x88\xa0\x1f\x00\"4\n\x0e\x43onsensusState\x12\x1c\n\ttimestamp\x18\x01 \x01(\x04R\ttimestamp:\x04\x88\xa0\x1f\x00\"c\n\x10\x41ttestationProof\x12)\n\x10\x61ttestation_data\x18\x01 \x01(\x0cR\x0f\x61ttestationData\x12\x1e\n\nsignatures\x18\x02 \x03(\x0cR\nsignatures:\x04\x88\xa0\x1f\x00\x42NZLgithub.com/cosmos/ibc-go/v10/modules/light-clients/attestations;attestationsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ibc.lightclients.attestations.v1.attestations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZLgithub.com/cosmos/ibc-go/v10/modules/light-clients/attestations;attestations'
  _globals['_CLIENTSTATE']._loaded_options = None
  _globals['_CLIENTSTATE']._serialized_options = b'\210\240\037\000'
  _globals['_CONSENSUSSTATE']._loaded_options = None
  _globals['_CONSENSUSSTATE']._serialized_options = b'\210\240\037\000'
  _globals['_ATTESTATIONPROOF']._loaded_options = None
  _globals['_ATTESTATIONPROOF']._serialized_options = b'\210\240\037\000'
  _globals['_CLIENTSTATE']._serialized_start=112
  _globals['_CLIENTSTATE']._serialized_end=288
  _globals['_CONSENSUSSTATE']._serialized_start=290
  _globals['_CONSENSUSSTATE']._serialized_end=342
  _globals['_ATTESTATIONPROOF']._serialized_start=344
  _globals['_ATTESTATIONPROOF']._serialized_end=443
# @@protoc_insertion_point(module_scope)
